# Site settings
title: "Few, but ripe..."
author: Brandon Williams
email: mbrandonw@hey.com
description: "Articles about math, functional programming and the Swift programming language."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.fewbutripe.com" # the base hostname & protocol for your site
twitter_username: mbrandonw
github_username:  mbrandonw

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
